# Generated by Django 3.2.13 on 2022-09-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('prescriptions', models.CharField(blank=True, max_length=255)),
                ('dosage', models.IntegerField(blank=True)),
            ],
        ),
    ]
